version: "1"
services:
  openhab:
    image: openhab/openhab:3.2.0
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./dockerdata/openhab_addons:/openhab/addons
      - ./dockerdata/openhab_conf:/openhab/conf
      - ./dockerdata/openhab_userdata:/openhab/userdata
    environment:
      - OPENHAB_HTTP_PORT: "8080"
      - OPENHAB_HTTPS_PORT: "8443"
      - EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      - PUID=1001
      - PGID=1001
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./dockerdata/opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - TZ=Europe/Berlin
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=/dev/ttyUSB0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
      - DECONZ_VNC_PASSWORD=changeme
      - DECONZ_UID=1001
      - DECONZ_GID=1001
      - DECONZ_START_VERBOSE=0
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
